name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    steps:
      - uses: actions/checkout@v4.2.1
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install -r api/requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.6.0
        with:
          flags: backend
