on: [push] # Add the missing "on" property here

jobs:
  test-api:
    runs-on: ubuntu-latest
    docker:
      - image: cimg/python:3.10.2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r api/requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov api.calculator
      - name: Upload coverage report
        uses: codecov/codecov-action@v2

  test-frontend:
    runs-on: ubuntu-latest
  docker:
      - image: cimg/node:17.6.0
   steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install requirements
        run: cd web && npm install
      - name: Run tests and collect coverage
        run: cd web && npm run test
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
